version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always

  rosblox-studio:
    image: ghcr.io/rosblox/studio:latest
    volumes:
      - ./studio/layout.json:/src/layout.json
    ports:
      - 8080:8080
    restart: always

  ros-rosbridge-suite:
    image: ghcr.io/rosblox/ros-rosbridge-suite:humble
    restart: always
    network_mode: "bridge"
    ports:
      - 9090:9090
    #ipc: host
    #pid: host
    environment:
      - UID=1000
      - GID=1000
    command: "su - ros /run.sh"

  ros-gscam:
    image: ghcr.io/rosblox/ros-gscam:humble
    restart: always
    volumes:
      - ./config/pipeline.launch.xml:/opt/ros/humble/share/gscam/examples/pipeline.launch.xml
    devices:
      - /dev/v4l/by-id/usb-PC-LM1E_PC-LM1E_PC-LM1E-video-index0:/dev/video0
    network_mode: "host"
    ipc: host
    pid: host
    environment:
      - UID=1000
      - GID=1000
    command: "su - ros /run.sh"
